var ITN2012 = {["Algeria",],
["Angola",34],
["Benin",100],
["Botswana",21],
["Burkina Faso",87],
["Burundi",100],
["Cabo Verde",],
["Cameroon",71],
["Central African Republic",39],
["Chad",56],
["Comoros",68],
["Congo",71],
["Cote d'Ivoire",75],
["Democratic Republic of the Congo",90],
["Equatorial Guinea",2],
["Eritrea",35],
["Ethiopia",71],
["Gabon",],
["Gambia",100],
["Ghana",93],
["Guinea",3],
["Guinea-Bissau",34],
["Kenya",79],
["Liberia",74],
["Madagascar",76],
["Malawi",100],
["Mali",86],
["Mauritania",54],
["Mayotte France",100],
["Mozambique",53],
["Namibia",30],
["Niger",19],
["Nigeria",54],
["Rwanda",100],
["Sao Tome and Principe",100],
["Senegal",44],
["Sierra Leone",100],
["South Africa",],
["Swaziland",83],
["Togo",84],
["Uganda",45],
["United Republic of Tanzania",],
["Mainland",95],
["Zanzibar",93],
["Zambia",94],
["Zimbabwe",46],
["Argentina",],
["Belize",],
["Bolivia (Plurinational State of)",39],
["Brazil",18],
["Colombia",16],
["Costa Rica",49],
["Dominican Republic",88],
["Ecuador",87],
["El Salvador",],
[""French Guiana",[" France"",],
["Guatemala",50],
["Guyana",28],
["Haiti",100],
["Honduras",7],
["Mexico",100],
["Nicaragua",100],
["Panama",],
["Paraguay",],
["Peru",],
["Suriname",32],
["Venezuela (Bolivarian Republic of)",3],
["Afghanistan",98],
["Djibouti",23],
["Iran (Islamic Republic of)",17],
["Pakistan",2],
["Saudi Arabia",46],
["Somalia",20],
["South Sudan",60],
["Sudan",22],
["Yemen",31],
["Azerbaijan",18],
["Kyrgyzstan",100],
["Tajikistan",100],
["Turkey",],
["Uzbekistan",100],
["Bangladesh",89],
["Bhutan",100],
["Democratic People's Republic of Korea",43],
["India",6],
["Indonesia",26],
["Myanmar",35],
["Nepal",100],
["Sri Lanka",53],
["Thailand",23],
["Timor-Leste",45],
["Cambodia",100],
["China",100],
["Lao People's Democratic Republic",84],
["Malaysia",100],
["Papua New Guinea",86],
["Philippines",100],
["Republic of Korea",1],
["Solomon Islands",100],
["Vanuatu",100],
["Viet Nam",18]
};